services:
  db:
    build: mysql
    container_name: db
    platform: linux/amd64
    environment:
            MYSQL_DATABASE: bitrix
            MYSQL_USER: bitrix
            MYSQL_PASSWORD: 123
            MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./dump:/home

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    